login:
    path:     /login
    defaults: { _controller: BlogBundle:User:login }
    
login_check:
    path:     /login_check
    
logout:
    path:     /logout
    defaults: { _controller: BlogBundle:User:logout }
    
blog_homepage:
    path:     /{page}
    defaults: { _controller: BlogBundle:Entry:index, page:1 }
    
blog_add_tag:
    path:     /tags/add
    defaults: { _controller: BlogBundle:Tag:add }
    
blog_index_tag:
    path:     /tags
    defaults: { _controller: BlogBundle:Tag:index }
 
blog_delete_tag:
    path:     /tags/delete/{id}
    defaults: { _controller: BlogBundle:Tag:delete }
    
blog_add_category:
    path:     /categories/add
    defaults: { _controller: BlogBundle:Category:add }

blog_edit_category:
    path:     /categories/edit/{id}
    defaults: { _controller: BlogBundle:Category:edit }
    
blog_index_category:
    path:     /categories
    defaults: { _controller: BlogBundle:Category:index }
 
blog_delete_category:
    path:     /categories/delete/{id}
    defaults: { _controller: BlogBundle:Category:delete }
    
blog_add_entry:
    path:     /entries/add
    defaults: { _controller: BlogBundle:Entry:add }
    
blog_edit_entry:
    path:     /entries/edit/{id}
    defaults: { _controller: BlogBundle:Entry:edit }
    
blog_delete_entry:
    path:     /entries/delete/{id}
    defaults: { _controller: BlogBundle:Entry:delete }
    
